/*
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*
*/
package org.apache.airavata.datacat.parsers.gridchem.gfinalcoord;
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Sep 10 09:08:56 IST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class GFinalCoordSym {
  /* terminals */
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int INPUT6 = 9;
  public static final int INPUT5 = 8;
  public static final int INPUT4 = 7;
  public static final int SCFDONE = 5;
  public static final int INPUT3 = 6;
  public static final int FOUNDITER = 4;
  public static final int INPUT2 = 3;
  public static final int INPUT1 = 2;
}

