/*
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*
*/
package org.apache.airavata.datacat.parsers.gridchem.mp2to5c;
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Sep 14 12:10:10 IST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class MP2to5cSym {
  /* terminals */
  public static final int E4_SDTQ = 8;
  public static final int MP2OPT = 16;
  public static final int LIM = 18;
  public static final int UMP4_SDQ = 11;
  public static final int UMP4_SDTQ = 12;
  public static final int E4_DQ = 6;
  public static final int FCOPT = 13;
  public static final int UMP4_DQ = 10;
  public static final int E4_SDQ = 7;
  public static final int E3 = 5;
  public static final int E2 = 2;
  public static final int FLOAT = 19;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MP4_T = 4;
  public static final int FCOPT2 = 14;
  public static final int ALGOPT = 15;
  public static final int VAR = 17;
  public static final int EUMP3 = 9;
  public static final int EUMP2 = 3;
}

