#---------- set the base image to Ubuntu
FROM ubuntu

#---------- file Author / Maintainer
MAINTAINER GSoC Pankaj Saha

#---------- update the repository sources list
RUN apt-get update

#---------- setting the work directory as users home
WORKDIR /

#---------- installing jdk8
RUN apt-get install wget -y
RUN wget --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
RUN mkdir opt/jdk
RUN tar -zxf jdk-8u5-linux-x64.tar.gz -C opt/jdk
RUN update-alternatives --install /usr/bin/java java /opt/jdk/jdk1.8.0_05/bin/java 100
RUN update-alternatives --install /usr/bin/javac javac /opt/jdk/jdk1.8.0_05/bin/javac 100


#ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
#ENV PATH $JAVA_HOME/bin:$PATH
#RUN echo $JAVA_HOME
#RUN echo $PATH



#--------- installing maven
RUN apt-get update
RUN apt-get install maven -y

#--------- installing git
RUN apt-get install git -y

#--------- downloading airavata server
RUN mkdir git
WORKDIR /git
RUN git clone https://github.com/apache/airavata.git
WORKDIR /git/airavata
#RUN git checkout airavata-0.15-release-branch
RUN git checkout e131c34a0543f9
RUN mvn clean install -Dmaven.skip.test=true
WORKDIR /git/airavata/modules/distribution/server/target
RUN tar -zxvf apache-airavata-server-0.15-SNAPSHOT-bin.tar.gz
WORKDIR /git/airavata/modules/distribution/server/target/apache-airavata-server-0.15-SNAPSHOT/bin

#--------- adding entry point script file
ADD airavata_startup.sh airavata_startup.sh

#--------- starting the airavata service


CMD bash -C '/git/airavata/modules/distribution/server/target/apache-airavata-server-0.15-SNAPSHOT/bin/airavata_startup.sh';'bash'
#CMD bash -C 'bash'

#--------- exposing port
EXPOSE 8930
