/*
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*
*/
package org.apache.airavata.datacat.parsers.gridchem.scfb;
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Sep 15 16:04:59 IST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class SCFbSym {
  /* terminals */
  public static final int TEE = 12;
  public static final int EQUALS = 34;
  public static final int PE = 32;
  public static final int GTEF = 20;
  public static final int INT = 37;
  public static final int LEAVE = 36;
  public static final int LTEF = 19;
  public static final int SCFDONE = 25;
  public static final int CONVG = 27;
  public static final int DUMMY = 35;
  public static final int IS = 15;
  public static final int PASS = 5;
  public static final int ERR = 21;
  public static final int MAXDP = 23;
  public static final int S2 = 28;
  public static final int ATCYCLE = 10;
  public static final int IE = 16;
  public static final int EOF = 0;
  public static final int COEFF = 11;
  public static final int RMSDP = 22;
  public static final int IDIAG = 6;
  public static final int error = 1;
  public static final int ERHF = 26;
  public static final int NO09 = 17;
  public static final int FOUNDLENX = 3;
  public static final int COLON = 24;
  public static final int GAP = 13;
  public static final int DELTAE = 8;
  public static final int NK = 14;
  public static final int EE = 33;
  public static final int DIIS = 9;
  public static final int LENXINT = 38;
  public static final int FLOAT = 39;
  public static final int KE = 31;
  public static final int MINUSVT = 29;
  public static final int NV01 = 18;
  public static final int AU = 30;
  public static final int FOUNDSCF = 2;
  public static final int CYCLE = 4;
  public static final int ENERGY = 7;
}

