apiVersion: apps/v1beta2 # for versions before 1.7.0 use apps/v1beta1
kind: Deployment
metadata:
  name: data-in-task
  labels:
    app: data-in-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-in-task
  template:
    metadata:
      labels:
        app: data-in-task
    spec:
      containers:
      - name: data-in-task
        image: dimuthuupe/data-in-task:v1.0
        env:
        - name: zookeeper_connection_url
          value: zk.default.svc.cluster.local:2199
        - name: participant_name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8080