apiVersion: v1
kind: Service
metadata:
  name: zk
  labels:
    name: zk
spec:
  ports:
    - port: 2199
      targetPort: 2199
      protocol: TCP
      name: zk
---

kind: Endpoints
apiVersion: v1
metadata:
  name: zk
subsets:
  - addresses:
      - ip: 192.168.1.114
    ports:
      - port: 2199
        name: zk