# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_comments',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='request',
            name='cpu_hours_allocated',
        ),
        migrations.RemoveField(
            model_name='request',
            name='cpu_hours_requested',
        ),
        migrations.AddField(
            model_name='request',
            name='applications_to_be_used',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='disk_usage_range_per_job',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='field_of_science',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='keywords',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='max_memory_per_cpu',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='num_cpus_per_job',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='request_reviewed_and_funded_by',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='service_units',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='specific_resource_selection',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='typical_su_per_job',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
