# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171201_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
