# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171201_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_date',
        ),
    ]
