# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61lc_info.proto\x12\ncom.smiles\"u\n\x08\x43\x61lcInfo\x12\x0e\n\x06nbasis\x18\x01 \x01(\x03\x12\x0b\n\x03nmo\x18\x02 \x01(\x03\x12\x0e\n\x06nalpha\x18\x03 \x01(\x03\x12\r\n\x05nbeta\x18\x04 \x01(\x03\x12\r\n\x05natom\x18\x05 \x01(\x03\x12\x0e\n\x06\x65nergy\x18\x06 \x01(\x01\x12\x0e\n\x06SMILES\x18\x07 \x01(\t\"P\n\x0f\x43\x61lcInfoRequest\x12\x15\n\rcalcInfoQuery\x18\x01 \x01(\t\x12&\n\x08\x63\x61lcInfo\x18\x02 \x01(\x0b\x32\x14.com.smiles.CalcInfo2\xaa\x02\n\x0f\x43\x61lcInfoService\x12\x42\n\x0bGetCalcInfo\x12\x1b.com.smiles.CalcInfoRequest\x1a\x14.com.smiles.CalcInfo\"\x00\x12\x45\n\x0e\x43reateCalcInfo\x12\x1b.com.smiles.CalcInfoRequest\x1a\x14.com.smiles.CalcInfo\"\x00\x12\x45\n\x0eUpdateCalcInfo\x12\x1b.com.smiles.CalcInfoRequest\x1a\x14.com.smiles.CalcInfo\"\x00\x12\x45\n\x0e\x44\x65leteCalcInfo\x12\x1b.com.smiles.CalcInfoRequest\x1a\x14.com.smiles.CalcInfo\"\x00\x62\x06proto3')



_CALCINFO = DESCRIPTOR.message_types_by_name['CalcInfo']
_CALCINFOREQUEST = DESCRIPTOR.message_types_by_name['CalcInfoRequest']
CalcInfo = _reflection.GeneratedProtocolMessageType('CalcInfo', (_message.Message,), {
  'DESCRIPTOR' : _CALCINFO,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:com.smiles.CalcInfo)
  })
_sym_db.RegisterMessage(CalcInfo)

CalcInfoRequest = _reflection.GeneratedProtocolMessageType('CalcInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALCINFOREQUEST,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:com.smiles.CalcInfoRequest)
  })
_sym_db.RegisterMessage(CalcInfoRequest)

_CALCINFOSERVICE = DESCRIPTOR.services_by_name['CalcInfoService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALCINFO._serialized_start=31
  _CALCINFO._serialized_end=148
  _CALCINFOREQUEST._serialized_start=150
  _CALCINFOREQUEST._serialized_end=230
  _CALCINFOSERVICE._serialized_start=233
  _CALCINFOSERVICE._serialized_end=531
# @@protoc_insertion_point(module_scope)
