# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63\x61lc_info.proto\x12\x08\x63\x61lcInfo\"\x8a\x01\n\x08\x43\x61lcInfo\x12\x13\n\x0b\x63\x61lcinfo_id\x18\x01 \x01(\t\x12\x0e\n\x06smiles\x18\x02 \x01(\t\x12\x0e\n\x06nbasis\x18\x03 \x01(\x03\x12\x0b\n\x03nmo\x18\x04 \x01(\x03\x12\x0e\n\x06nalpha\x18\x05 \x01(\x03\x12\r\n\x05nbeta\x18\x06 \x01(\x03\x12\r\n\x05natom\x18\x07 \x01(\x03\x12\x0e\n\x06\x65nergy\x18\x08 \x01(\x01\"9\n\x11\x43reateInfoRequest\x12$\n\x08\x63\x61lcInfo\x18\x01 \x01(\x0b\x32\x12.calcInfo.CalcInfo\":\n\x12\x43reateInfoResponse\x12$\n\x08\x63\x61lcInfo\x18\x01 \x01(\x0b\x32\x12.calcInfo.CalcInfo\"\x1d\n\x0fReadInfoRequest\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\x10ReadInfoResponse\x12$\n\x08\x63\x61lcInfo\x18\x01 \x01(\x0b\x32\x12.calcInfo.CalcInfo\"9\n\x11UpdateInfoRequest\x12$\n\x08\x63\x61lcInfo\x18\x01 \x01(\x0b\x32\x12.calcInfo.CalcInfo\":\n\x12UpdateInfoResponse\x12$\n\x08\x63\x61lcInfo\x18\x01 \x01(\x0b\x32\x12.calcInfo.CalcInfo\"(\n\x11\x44\x65leteInfoRequest\x12\x13\n\x0b\x63\x61lcInfo_id\x18\x01 \x01(\t\")\n\x12\x44\x65leteInfoResponse\x12\x13\n\x0b\x63\x61lcInfo_id\x18\x01 \x01(\t\"\x11\n\x0fListInfoRequest\"8\n\x10ListInfoResponse\x12$\n\x08\x63\x61lcInfo\x18\x01 \x01(\x0b\x32\x12.calcInfo.CalcInfo2\x92\x03\n\x0f\x43\x61lcInfoService\x12M\n\x0e\x43reateCalcinfo\x12\x1b.calcInfo.CreateInfoRequest\x1a\x1c.calcInfo.CreateInfoResponse\"\x00\x12G\n\x0cReadCalcInfo\x12\x19.calcInfo.ReadInfoRequest\x1a\x1a.calcInfo.ReadInfoResponse\"\x00\x12M\n\x0eUpdateCalcInfo\x12\x1b.calcInfo.UpdateInfoRequest\x1a\x1c.calcInfo.UpdateInfoResponse\"\x00\x12M\n\x0e\x44\x65leteCalcInfo\x12\x1b.calcInfo.DeleteInfoRequest\x1a\x1c.calcInfo.DeleteInfoResponse\"\x00\x12I\n\x0cListCalcInfo\x12\x19.calcInfo.ListInfoRequest\x1a\x1a.calcInfo.ListInfoResponse\"\x00\x30\x01\x62\x06proto3')



_CALCINFO = DESCRIPTOR.message_types_by_name['CalcInfo']
_CREATEINFOREQUEST = DESCRIPTOR.message_types_by_name['CreateInfoRequest']
_CREATEINFORESPONSE = DESCRIPTOR.message_types_by_name['CreateInfoResponse']
_READINFOREQUEST = DESCRIPTOR.message_types_by_name['ReadInfoRequest']
_READINFORESPONSE = DESCRIPTOR.message_types_by_name['ReadInfoResponse']
_UPDATEINFOREQUEST = DESCRIPTOR.message_types_by_name['UpdateInfoRequest']
_UPDATEINFORESPONSE = DESCRIPTOR.message_types_by_name['UpdateInfoResponse']
_DELETEINFOREQUEST = DESCRIPTOR.message_types_by_name['DeleteInfoRequest']
_DELETEINFORESPONSE = DESCRIPTOR.message_types_by_name['DeleteInfoResponse']
_LISTINFOREQUEST = DESCRIPTOR.message_types_by_name['ListInfoRequest']
_LISTINFORESPONSE = DESCRIPTOR.message_types_by_name['ListInfoResponse']
CalcInfo = _reflection.GeneratedProtocolMessageType('CalcInfo', (_message.Message,), {
  'DESCRIPTOR' : _CALCINFO,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:calcInfo.CalcInfo)
  })
_sym_db.RegisterMessage(CalcInfo)

CreateInfoRequest = _reflection.GeneratedProtocolMessageType('CreateInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEINFOREQUEST,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:calcInfo.CreateInfoRequest)
  })
_sym_db.RegisterMessage(CreateInfoRequest)

CreateInfoResponse = _reflection.GeneratedProtocolMessageType('CreateInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEINFORESPONSE,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:calcInfo.CreateInfoResponse)
  })
_sym_db.RegisterMessage(CreateInfoResponse)

ReadInfoRequest = _reflection.GeneratedProtocolMessageType('ReadInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _READINFOREQUEST,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:calcInfo.ReadInfoRequest)
  })
_sym_db.RegisterMessage(ReadInfoRequest)

ReadInfoResponse = _reflection.GeneratedProtocolMessageType('ReadInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _READINFORESPONSE,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:calcInfo.ReadInfoResponse)
  })
_sym_db.RegisterMessage(ReadInfoResponse)

UpdateInfoRequest = _reflection.GeneratedProtocolMessageType('UpdateInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEINFOREQUEST,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:calcInfo.UpdateInfoRequest)
  })
_sym_db.RegisterMessage(UpdateInfoRequest)

UpdateInfoResponse = _reflection.GeneratedProtocolMessageType('UpdateInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEINFORESPONSE,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:calcInfo.UpdateInfoResponse)
  })
_sym_db.RegisterMessage(UpdateInfoResponse)

DeleteInfoRequest = _reflection.GeneratedProtocolMessageType('DeleteInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEINFOREQUEST,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:calcInfo.DeleteInfoRequest)
  })
_sym_db.RegisterMessage(DeleteInfoRequest)

DeleteInfoResponse = _reflection.GeneratedProtocolMessageType('DeleteInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEINFORESPONSE,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:calcInfo.DeleteInfoResponse)
  })
_sym_db.RegisterMessage(DeleteInfoResponse)

ListInfoRequest = _reflection.GeneratedProtocolMessageType('ListInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTINFOREQUEST,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:calcInfo.ListInfoRequest)
  })
_sym_db.RegisterMessage(ListInfoRequest)

ListInfoResponse = _reflection.GeneratedProtocolMessageType('ListInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTINFORESPONSE,
  '__module__' : 'calc_info_pb2'
  # @@protoc_insertion_point(class_scope:calcInfo.ListInfoResponse)
  })
_sym_db.RegisterMessage(ListInfoResponse)

_CALCINFOSERVICE = DESCRIPTOR.services_by_name['CalcInfoService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALCINFO._serialized_start=30
  _CALCINFO._serialized_end=168
  _CREATEINFOREQUEST._serialized_start=170
  _CREATEINFOREQUEST._serialized_end=227
  _CREATEINFORESPONSE._serialized_start=229
  _CREATEINFORESPONSE._serialized_end=287
  _READINFOREQUEST._serialized_start=289
  _READINFOREQUEST._serialized_end=318
  _READINFORESPONSE._serialized_start=320
  _READINFORESPONSE._serialized_end=376
  _UPDATEINFOREQUEST._serialized_start=378
  _UPDATEINFOREQUEST._serialized_end=435
  _UPDATEINFORESPONSE._serialized_start=437
  _UPDATEINFORESPONSE._serialized_end=495
  _DELETEINFOREQUEST._serialized_start=497
  _DELETEINFOREQUEST._serialized_end=537
  _DELETEINFORESPONSE._serialized_start=539
  _DELETEINFORESPONSE._serialized_end=580
  _LISTINFOREQUEST._serialized_start=582
  _LISTINFOREQUEST._serialized_end=599
  _LISTINFORESPONSE._serialized_start=601
  _LISTINFORESPONSE._serialized_end=657
  _CALCINFOSERVICE._serialized_start=660
  _CALCINFOSERVICE._serialized_end=1062
# @@protoc_insertion_point(module_scope)
